root: true
env:
  browser: true
  node: true
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:nuxt/recommended
  - plugin:prettier/recommended
plugins:
  - vue
  - nuxt
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      semi: false
  no-console: warn
  no-debugger: warn